### ISSUE TITLE
Plans to add no_std support?

### ISSUE THREAD

**Issue by drewstone** [matter-labs/eip1962#12]
It's mentioned but is it live?

Also happy to discuss funding options to get this implemented if it isn't.

**Comment by shamatar** [comment]
Hello Drew!

In principle there are only one thing that prevent core functionality from being no_std: vectors in some places.Those can be replaced by something like arrayvec with a reasonable bound. I didn't do it cause there was no feedback or direct demand for it. 

If you also want to make things like mapping "field-to-curve" compatible with no_std then it would require a little more tinkering due to once_cell and BigUint. 

First part I will fix eventually (no time estimates), but not sure about the second one.

**Comment by drewstone** [comment]
Awesome to hear @shamatar, let me know if there's interest in setting this up as an Edgeware grant and I'd be happy to propose it to our Treasury/democracy system.

With regards to BigUint, I believe there's a no_std feature of `num` to handle arithmetic without the `std` lib but don't know much about `once_cell`.

**Comment by shamatar** [comment]
Hello Drew. 

I've missed you comment last week, but in general I'd welcome a grant proposal even though it's unlikely that I'd do this changes myself. Ideally someone more familiar with no_std would be much better candidate here.

**Comment by drewstone** [comment]
I should have a PR up now @shamatar for no_std support.
